<?php

// add enabled to defaults

/**
 * Implements hook_menu().
 *
 * @see
 */
function tour_ui_menu() {
  $items = array();

  $items['admin/config/user-interface/tour'] = array(
    'title' => 'tour',
    'page callback' => 'tour_ui_list_tour_tours',
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/user-interface/tour/ui'] = array(
    'title' => 'tour UI',
    'access arguments' => array('access administration pages'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  $items['admin/config/user-interface/tour/ui/%'] = array(
    'title' => 'tour Editor',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('tour_ui_edit_tour', 5),
    'access arguments' => array('access administration pages'),
  );
	$items['admin/config/user-interface/tour/ui/%/disable'] = array(
		'title' => 'Disable tour',
		'page callback' => 'backdrop_get_form',
		'page arguments' => array('tour_ui_disable_tour', 5),
    'access arguments' => array('access administration pages'),
		'type' => MENU_CALLBACK,
	);  
  $items['admin/config/user-interface/tour/ui/add'] = array(
    'title' => 'Add new tour',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('tour_ui_edit_tour', 5),
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_ACTION,
  );
  
  $items['admin/config/user-interface/tour/demo'] = array(
    'title' => 'tour Demo (Start tour automatically)',
    'page callback' => 'theme',
    'page arguments' => array('tour_demo'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/config/user-interface/tour/demo/auto-start'] = array(
    'title' => 'tour Demo (Start tour automatically)',
    'access arguments' => array('access administration pages'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/config/user-interface/tour/demo/manual-trigger'] = array(
    'title' => 'tour Demo (Use manual trigger to start tour)',
    'page callback' => 'theme',
    'page arguments' => array('tour_demo'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Menu callback.
 * Returns an administrative overview of all tours.
 *
 */
function tour_ui_list_tour_tours() {
  $items = tour_load_all();
  $rows = array();
  dpm($items);
  foreach ($items as $name => $item) {
    // Set variable for enabled state.
    $state = $item['enabled'] ? 'Enabled' : 'Disabled';
    
    $row['title'] = $item['title'];
    $row['description'] = $item['description'];
    $row['auto_start'] = $item['auto_start'] ? 'TRUE' : 'FALSE';
    $row['edit'] = (!$item['editable']) ? 'Not editable' : l('edit', 'admin/config/user-interface/tour/ui/' . $name);
    $row['disable'] = t("!state (!url)", array('!state' => $state, '!url' => l(t('change'), 'admin/config/user-interface/tour/ui/' . $name . '/disable')));
    $rows[] = $row;
  }
  if (!empty($rows)) {
    $header = array(
      t('Title'),
      t('Description'),
      t('Autostart'),
      t('Edit link'),
      t('Disable'),
    );
    $output = theme('table', array('header' => $header, 'rows' => $rows));
    return $output;
  }
  else {
    return t('There are no tours.');
  }
}

/**
 * Menu callback.
 * Returns the confirm form to disable a tour.
 *
 */
function tour_ui_disable_tour($form, &$form_state, $name) {
  $tour = tour_load($name);
	$form = array();
	$form['tour'] = array(
		'#type' => 'value',
		'#value' => $tour,
	);
  $set_enabled_status = $tour['enabled'] ? 'disable' : 'enable';
  return confirm_form(
    $form,
    t("Are you sure you want to !disable this tour?", array('!disable' => $set_enabled_status)),
    'admin/config/user-interface/tour',
    t(''),
    t('!disable', array('!disable' => $set_enabled_status)),
    t('Cancel')
  );
}

/**
 * Submit handler for tour_ui_disable_tour.
 * This function is invoked only when the user clicks confirm button
 * clicking on cancel, the user goes back to the $path.
 */
function tour_ui_disable_tour_submit($form, &$form_state) {
  $tour = $form['tour']['#value'];

  $set_enabled_status = $tour['enabled'] ? 0 : 1;
  $config = config($tour['config_name']);
  $config->set('enabled', $set_enabled_status);
  $config->save();

	backdrop_set_message('Tour ' . $tour['title'] . ' settings saved.');
  cache_flush('cache');
	$form_state['redirect'] = 'admin/config/user-interface/tour';
}

/**
 * Returns a form to edit a tour.
 *
 */
function tour_ui_edit_tour($form, &$form_state, $name) {
  $form['#tree'] = TRUE;
  
  $tour = array();
  if($name && $tour = tour_load($name)) {
    backdrop_set_title($tour['title']);

    $form['title'] = array(
      '#type' => 'textfield',
      '#title' => t('Title'),
      '#default_value' => isset($tour['title']) ? $tour['title'] : '',
    );
    $form['config_name'] = array(
      '#type' => 'value',
      '#value' => $tour['config_name'],
    );
    $form['name'] = array(
      '#type' => 'value',
      '#value' => $tour['name'],
    );
    $form['editable'] = array(
      '#type' => 'value',
      '#value' => $tour['editable'],
    );
  }
  elseif($name =='add') {
    $form['title'] = array(
      '#type' => 'textfield',
      '#title' => t('Title'),
      '#default_value' => isset($tour['title']) ? $tour['title'] : '',
    );
    $form['name'] = array(
      '#type' => 'name',
      '#default_value' => '',
      '#maxlength' => 21,
      '#name' => array(
        'exists' => 'tour_name_exists',
        'source' => array('title'), 
      ),
    );
    $form['editable'] = array(
      '#type' => 'checkbox',
      '#title' => t('Editable'),
      '#default_value' => 1,
    );
  }
  else {
    return array();
  }
  
  $form['name'] = array(
    '#type' => 'value',
    '#value' => $name,
  );
  $form['paths'] = array(
    '#type' => 'textarea',
    '#title' => t('Paths'),
    '#rows' => 3,
    '#default_value' => isset($tour['paths']) ? implode("\n", $tour['paths']) : '',
    '#description' => t('Enter one path per line, for example "node/1" or @front for the front page.', array('@front' => '<front>')),
    '#required' => TRUE,
  );
  $form['description'] = array(
    '#type' => 'textarea',
    '#title' => t('Description'),
    '#rows' => 3,
    '#default_value' => isset($tour['description']) ? $tour['description'] : '',
  );
  $form['auto_start'] = array(
    '#type' => 'checkbox',
    '#title' => t('Auto Start'),
    '#default_value' => isset($tour['auto_start']) ? $tour['auto_start'] : '',
  );
  $form['play_once'] = array(
    '#type' => 'checkbox',
    '#title' => t('Play Once'),
    '#default_value' => isset($tour['play_once']) ? $tour['play_once'] : '',
  );
  $form['enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enabled'),
    '#default_value' => isset($tour['enabled']) ? $tour['enabled'] : 1,
  );
  $form['content'] = array(
    '#type' => 'fieldset',
    '#title' => t('People coming to the picnic'),
    // Set up the wrapper so that AJAX will be able to replace the fieldset.
    '#prefix' => '<div id="steps-fieldset-wrapper">',
    '#suffix' => '</div>',
  );
  if (empty($form_state['content'])) {
    if($name == 'add') {
      $form_state['content'][0] = tour_ui_get_default_step();
    }
    else {
      $form_state['content'] = $tour['content'];
    }
  }
  
  foreach ($form_state['content'] as $i => $step) {
    $form['content'][$i]['title'] = array(
      '#type' => 'textfield',
      '#title' => t('Tip title'),
      '#default_value' => isset($step['title']) ? $step['title'] : '',
    );
    $form['content'][$i]['content'] = array(
      '#type' => 'textarea',
      '#title' => t('Tip content'),
      '#rows' => 2,
      '#default_value' => isset($step['content']) ? $step['content'] : '',
    );
    $form['content'][$i]['target'] = array(
      '#type' => 'textfield',
      '#title' => t('Target'),
      '#default_value' => isset($step['target']) ? $step['target'] : '',
    );
    $form['content'][$i]['placement'] = array(
      '#type' => 'select',
      '#title' => t('Placement'),
      '#options' => backdrop_map_assoc(array('top', 'bottom', 'right', 'left')),
      '#default_value' => isset($step['placement']) ? $step['placement'] : '',
    );
    $form['content'][$i]['optional'] = array(
      '#type' => 'textarea',
      '#title' => t('Optional fields'),
      '#rows' => 4,
      '#default_value' => isset($step['optional']) && !empty($step['optional']) ? _rebuild_step_options($step['optional']) : '',
      '#description' => t('Enter one key:value per line, for example "xOffset: 15" (without the quotes)'),
    );
    $form['content'][$i]['weight'] = array(
      '#type' => 'weight',
      '#title' => t('Weight'),
      '#default_value' => isset($step['weight']) ? $step['weight'] : 10,
      '#delta' => 10,
      '#title_display' => 'invisible',
    );
    $form['content'][$i]['delete'] = array(
      '#type' => 'checkbox',
      '#title' => t('Delete'),
      '#default_value' => 0,
    );
  }
  $form['content']['add_more'] = array(
    '#type' => 'submit',
    '#value' => t('Add one more'),
    '#submit' => array('tour_ui_add_one'),
    '#limit_validation_errors' => array(), 
    // '#ajax' => array(
      // 'callback' => 'tour_ui_add_more_callback',
      // 'wrapper' => 'steps-fieldset-wrapper',
    // ),
  );
  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array('#type' => 'submit', '#value' => t('Save Changes'));
  return $form;
}

/**
 * Render API callback: Checks if a field machine name is taken.
 *
 * @param $value
 *   The machine name, not prefixed with 'field_'.
 *
 * @return
 *   Whether or not the field machine name is taken.
 */
function tour_name_exists($value) {
  $tours = tour_load_all();
  return isset($tours[$value]);
}

/**
 * Callback for both ajax-enabled buttons.
 *
 * Selects and returns the fieldset with the names in it.
 */
function tour_ui_add_more_callback($form, $form_state) {
  // Doesnt work
  return $form['content'];
}

/**
 * Callback for both populating step options textareas.
 *
 * Rebuilds options in the format 'stepOption:value'.
 */
function _rebuild_step_options($optionals) {
  $lines = array();
  foreach($optionals as $key => $option) {
    $lines[] = $key . ':' . $option;
  }
  return implode("\n", $lines);
}

/**
 * Submit handler for the "add-one-more" button.
 *
 * Increments the max counter and causes a rebuild.
 */
function tour_ui_add_one($form, &$form_state) {
  $max_weight = tour_ui_max_weight($form_state['content']);
  $form_state['content'][] = tour_ui_get_default_step($max_weight);
  $form_state['rebuild'] = TRUE;
}

function tour_ui_max_weight($content) {
  $weights = array();
  foreach($content as $step) {
    $weights[] = $step['weight'];
  }
  return max($weights);
}
function tour_ui_get_default_step($max_weight = 0) {
  return array (
    'title' => '',
    'content' => '',
    'target' => '',
    'placement' => '',
    'optional' => '',
    'weight' => $max_weight + 1,
  );
}

/**
 * Form validation handler for tour_ui_edit_tour().
 *
 * @see tour_ui_edit_tour_submit().
 */
function tour_ui_edit_tour_validate($form, &$form_state) {
  form_state_values_clean($form_state);
  
  unset($form_state['values']['actions']);
  
  // Cleanup multiline textareas
  $paths = tour_ui_format_lines($form_state['values']['paths']);
  
  // Validate paths
  foreach($paths as $path) {
    if(!menu_get_item($path) && $path != '<front>'){
      form_set_error('paths', t('The path @path is invalid.', array('@path' => $path)));
    }
  }
  $form_state['values']['paths'] = $paths;
  
  if(is_null($form_state['values']['content']) || (count($form_state['values']['content']) == 1 && $form_state['values']['content'][0]['delete'] == 1)) {
    form_set_error('form', 'No steps to save');
  }
  
  foreach($form_state['values']['content'] as $key => $content) {
    // Validate the optional settings textarea. Settings are input as one 
    // key:value pair per line. We need to separate each line, then convert the 
    // key:value string into array key and value.
    
    // First split the lines.
    $optionals = tour_ui_format_lines($form_state['values']['content'][$key]['optional']);
    $options = array();
    // If we got some lines, now split the pairs, using ":" as the delimiter
    if($optionals) {
      foreach($optionals as $option) {
        $split = explode(":", $option, 2);
        if(isset( $split[1])) {
          $options[$split[0]] = $split[1];
        }
        else {
          // If the split didnt return a value then the delimiter was missing,
          // or something else equally tragic. We bail out here.
          form_set_error('optional', 'One or more of your optional settings are invalid.');
        }
      }
    }
    $form_state['values']['content'][$key]['optional'] = $options;
    
    if(!$content['content'] && !$content['title']) {
      form_set_error('content', 'Steps must have a content or a title or both.');
    }

    if($content['delete']) {
      unset($form_state['values']['content'][$key]);
    }

    unset($form_state['values']['content'][$key]['delete']);
  }
} 

/**
 * Form submission handler for tour_ui_edit_tour().
 *
 * @see tour_ui_edit_tour_validate().
 */
function tour_ui_edit_tour_submit($form, &$form_state) {  
  $name = $form_state['values']['name'];
  unset($form_state['values']['name']);
  backdrop_sort($form_state['values']['content'], array('weight' => SORT_NUMERIC));
  $form_state['values']['content'] = array_values($form_state['values']['content']);
  $data = $form_state['values'];
  $tour = array();
  
  // This is a new tour being added.
  if($name == 'add') {
    $config = config('tour.tour.' . $form_state['values']['name']);
  }
  else {
    $config = config($form_state['values']['config_name']);
  }
  $config->set('tour', $data);
  $config->save();
  cache_flush('cache');
  $form_state['redirect'] = 'admin/config/user-interface/tour/ui';
}

/**
 * Cleans up input from multiline textareas.
 *
 */
function tour_ui_format_lines($text) {  
  // Cleanup text
  $text = explode("\n", $text);
  $text = array_map('trim', $text);
  $text = array_filter($text, 'strlen');
  return $text;
}

/**
 * Returns HTML for the tour edit form.
 *
 * @param $variables
 *   An associative array containing:
 *   - form: A render element representing the form.
 *
 * @ingroup themeable
 */
function theme_tour_ui_edit_tour($variables) {
  $form = $variables['form'];
  $rows = array();
  $output = '';
  $output .= backdrop_render($form['title']);
  if(isset($form['name'])) {
    $output .= backdrop_render($form['name']);
  }
  $output .= backdrop_render($form['paths']);
  $output .= backdrop_render($form['description']);
  $output .= backdrop_render($form['enabled']);
  $output .= backdrop_render($form['editable']);
  $output .= backdrop_render($form['auto_start']);
  $output .= backdrop_render($form['play_once']);
  
  $add_more = $form['content']['add_more'];
  unset($form['content']['add_more']);
  
  foreach (element_children($form['content']) as $id) {

    $form['content'][$id]['weight']['#attributes']['class'] = array('tour-ui-weight');
    $rows[] = array(
      'data' => array(
        theme('tour_content_row', $form['content'][$id]),
        backdrop_render($form['content'][$id]['delete']),
        backdrop_render($form['content'][$id]['weight']),
      ),
      'class' => array('draggable'),
    );
  }
  unset($form['content']);

  $header = array(t('Steps'), t('Delete'), t('Weight'));

  $table_id = 'tour-content';

  $output .= theme('table', array(
    'header' => $header,
    'rows' => $rows,
    'attributes' => array('id' => $table_id),
  ));
  $output .= backdrop_render($add_more);
  $output .= backdrop_render_children($form);

  backdrop_add_tabledrag($table_id, 'order', 'sibling', 'tour-ui-weight');

  return $output;
}

/**
 * Returns HTML for a single step in the tour edit form.
 *
 * @param $variables
 *   An associative array containing:
 *   - form: A render element representing the form.
 *
 * @ingroup themeable
 */
function theme_tour_content_row($content) {
    $row['title'] = backdrop_render($content['title']);
    $row['content'] = backdrop_render($content['content']);
    $row['target'] = backdrop_render($content['target']);
    $row['placement'] = backdrop_render($content['placement']);
    $rows = array($row);

    if (!empty($rows)) {
    $header = array();
    $output = theme('table', array('header' => $header, 'rows' => $rows));
    
    $attributes = backdrop_render($content['optional']);
    
    backdrop_add_js(backdrop_get_path('module', 'tour_ui') . '/tour_ui.js');
    $toggle = ' <a class="requirements-toggle" href="#">' . t('more') . '</a>';
    $details = '<div class="text table-filter-text-source"> ' . $toggle . '</div>' . '<div class="requirements">' . $attributes . '</div>';

    $output .= $details;
    return $output;
  }
  else {
    return t('There are no items in the queue.');
  }
}

/**
 * Implements hook_theme().
 *
 */
function tour_ui_theme() {
  return array(
    // Theme function for the 'simple' example.
    'tour_ui_edit_tour' => array(
      'render element' => 'form',
    ),
    'tour_content_row' => array(
      'render element' => NULL,
    ),
    'tour_demo' => array(
      'variables' => array(),
      'template' => 'templates/tour-demo',
    ),
  );
}

 /**
 * Implements hook_config_info().
 * Provides two tour files: one with default tours for demo purposes and one 
 * which is blank, for storing user-created tours.
 */
function tour_ui_config_info() {
  $prefixes['tour.tour.auto_start'] = array(
    'label' => t('tour Default Tour - Autostart'),
    'group' => t('tour'),
  );
  $prefixes['tour.tour.manual_trigger'] = array(
    'label' => t('tour Custom Tour- Manual trigger'),
    'group' => t('tour'),
  );
  return $prefixes;
}
