<?php

/**
 * Implements hook_menu().
 *
 * @see
 */
function tour_ui_menu() {
  $items = array();

  $items['admin/config/user-interface/tour'] = array(
    'title' => 'Tour',
    'page callback' => 'tour_ui_list_tour_tours',
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/user-interface/tour/ui'] = array(
    'title' => 'Tour UI',
    'access arguments' => array('access administration pages'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
	$items['admin/config/user-interface/tour/ui/%tour/disable'] = array(
		'title' => 'Disable tour',
		'page callback' => 'backdrop_get_form',
		'page arguments' => array('tour_ui_disable_tour', 5),
    'access arguments' => array('access administration pages'),
		'type' => MENU_CALLBACK,
	);  
	$items['admin/config/user-interface/tour/ui/%tour/delete'] = array(
		'title' => 'Delete tour',
		'page callback' => 'backdrop_get_form',
		'page arguments' => array('tour_ui_delete_tour', 5),
    'access arguments' => array('access administration pages'),
		'type' => MENU_CALLBACK,
	);  
  
  $items['admin/config/user-interface/tour/ui/%tour_ui_tempstore'] = array(
    'title' => 'Tour Editor',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('tour_ui_edit_tour', 5),
    'access arguments' => array('access administration pages'),
  );
  $items['admin/config/user-interface/tour/ui/add'] = array(
    'title' => 'Add new tour',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('tour_ui_edit_tour', 5),
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/config/user-interface/tour/ui/%tour_ui_tempstore/step/%'] = array(
    'title' => 'Edit step',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('tour_ui_edit_step', 5, 7),
    'access arguments' => array('access administration pages'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/user-interface/tour/ui/%tour_ui_tempstore/step/%/delete'] = array(
    'title' => 'Delete step',
    'page callback' => 'tour_ui_delete_step',
    'page arguments' => array(5, 7),
    'access arguments' => array('access administration pages'),
    'theme callback' => 'ajax_base_page_theme',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/user-interface/tour/ui/%tour_ui_tempstore/step/add'] = array(
    'title' => 'Add step',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('tour_ui_edit_step', 5, 7),
    'access arguments' => array('access administration pages'),
    'type' => MENU_CALLBACK,
  );
  
  $items['admin/config/user-interface/tour/demo'] = array(
    'title' => 'tour Demo (Start tour automatically)',
    'page callback' => 'theme',
    'page arguments' => array('tour_demo'),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/config/user-interface/tour/demo/auto-start'] = array(
    'title' => 'tour Demo (Start tour automatically)',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/config/user-interface/tour/demo/manual-trigger'] = array(
    'title' => 'tour Demo (Use manual trigger to start tour)',
    'page callback' => 'theme',
    'page arguments' => array('tour_demo'),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Menu callback.
 * Returns an administrative overview of all tours.
 *
 */
function tour_ui_list_tour_tours() {
  $items = tour_load_all();
  $rows = array();

  foreach ($items as $name => $item) {
    // Set variable for enabled state.
    $state = $item['enabled'] ? 'Enabled' : 'Disabled';
    $state_change = $item['enabled'] ? 'Disable' : 'Enable';

    $links = array();
    if ($item['editable']) {
      $links['edit'] = array(
        'title' => t('Edit'),
        'href' => 'admin/config/user-interface/tour/ui/' . $name,
      );
    }
    $links['disable'] = array(
      'title' => $state_change,
      'href' => 'admin/config/user-interface/tour/ui/' . $name . '/disable',
    );
    $links['delete'] = array(
      'title' => t('Delete'),
      'href' => 'admin/config/user-interface/tour/ui/' . $name . '/delete',
    );
    $operations = array(
      '#type' => 'dropbutton',
      '#links' => $links,
    );

    $tour_links = array();
    foreach ($item['paths'] as $path) {
      $tour_links[] = l($path, $path);
    }
    $row['title'] = check_plain($item['title']);
    $row['paths'] = theme('item_list', array('items' => $tour_links));
    $row['description'] = check_plain($item['description']);
    $row['auto_start'] = $item['auto_start'] ? 'TRUE' : 'FALSE';
    $row['status'] = $state;
    $row['operations'] = backdrop_render($operations);
    $rows[] = $row;
  }

  if (!empty($rows)) {
    $header = array(
      t('Title'),
      t('Paths'),
      t('Description'),
      t('Autostart'),
      t('Status'),
      t('Operations'),
    );
    $output = theme('table', array('header' => $header, 'rows' => $rows));
    return $output;
  }
  else {
    return t('There are no tours.');
  }
}

/**
 * Menu callback.
 * Returns the confirm form to disable a tour.
 *
 */
function tour_ui_disable_tour($form, &$form_state, $tour) {
	$form = array();
	$form['tour'] = array(
		'#type' => 'value',
		'#value' => $tour,
	);
  $set_enabled_status = $tour['enabled'] ? 'disable' : 'enable';
  return confirm_form(
    $form,
    t("Are you sure you want to !disable this tour?", array('!disable' => $set_enabled_status)),
    'admin/config/user-interface/tour',
    t(''),
    t('!disable', array('!disable' => $set_enabled_status)),
    t('Cancel')
  );
}

/**
 * Submit handler for tour_ui_disable_tour.
 * This function is invoked only when the user clicks confirm button
 * clicking on cancel, the user goes back to the $path.
 */
function tour_ui_disable_tour_submit($form, &$form_state) {
  $tour = $form_state['values']['tour'];

  $set_enabled_status = $tour['enabled'] ? 0 : 1;
  $config = config('tour.tour.' . $tour['name']);
  $config->set('enabled', $set_enabled_status);
  $config->save();

  backdrop_set_message(t('Tour "@title" settings saved.', array('@title' => $tour['title'])));
  cache_flush('cache');
	$form_state['redirect'] = 'admin/config/user-interface/tour';
}

/**
 * Menu callback.
 * Returns the confirm form to disable a tour.
 *
 */
function tour_ui_delete_tour($form, &$form_state, $tour) {
	$form = array();
	$form['tour'] = array(
		'#type' => 'value',
		'#value' => $tour,
	);

  return confirm_form(
    $form,
    t("Are you sure you want to delete this tour?"),
    'admin/config/user-interface/tour',
    t(''),
    t('Delete'),
    t('Cancel')
  );
}

/**
 * Submit handler for tour_ui_delete_tour.
 */
function tour_ui_delete_tour_submit($form, &$form_state) {
  $tour = $form_state['values']['tour'];

  $config = config('tour.tour.' . $tour['name']);
  $config->delete();

  backdrop_set_message(t('Tour "@title" has been deleted.', array('@title' => $tour['title'])));
  cache_flush('cache');
	$form_state['redirect'] = 'admin/config/user-interface/tour';
}

/**
 * Returns a form to edit a tour.
 *
 */
function tour_ui_edit_tour($form, &$form_state, $tour = 'add') {
  backdrop_add_css(backdrop_get_path('module', 'tour_ui') . '/css/tour.admin.css');

  $form['#tree'] = TRUE;
  $form['#attributes']['id'] = 'tour-edit-table';
  $form_state['is_new'] = ($tour == 'add');
  $message = t('This form has unsaved changes. Click "Save" to make changes permanent or "Cancel" to discard changes.');

  $form['messages'] = array(
    '#markup' => !empty($tour['locked']) ? '<div class="messages warning">' . $message . '</div>' : '',
    '#weight' => -100,
    // Prefix/suffix used to identify in AJAX requests.
    '#prefix' => '<div id="layout-messages">',
    '#suffix' => '</div>',
  );
  
  if($form_state['is_new']) {
    $form['title'] = array(
      '#type' => 'textfield',
      '#title' => t('Titles'),
      '#default_value' => isset($tour['title']) ? $tour['title'] : '',
    );
    $form['name'] = array(
      '#type' => 'machine_name',
      '#title' => t('Title'),
      '#default_value' => '',
      '#maxlength' => 21,
      '#machine_name' => array(
        'exists' => 'tour_name_exists',
        'source' => array('title'), 
      ),
    );
    $form['editable'] = array(
      '#type' => 'checkbox',
      '#title' => t('Editable'),
      '#default_value' => 1,
    );
  }
  else {
    backdrop_set_title($tour['title']);

    $form['title'] = array(
      '#type' => 'textfield',
      '#title' => t('Title'),
      '#default_value' => isset($tour['title']) ? $tour['title'] : '',
    );
    $form['name'] = array(
      '#type' => 'value',
      '#value' => $tour['name'],
    );
    $form['editable'] = array(
      '#type' => 'value',
      '#value' => $tour['editable'],
    );
  }
  $form_state['tour'] = $tour;
  
  $form['paths'] = array(
    '#type' => 'textarea',
    '#title' => t('Paths'),
    '#rows' => 3,
    '#default_value' => isset($tour['paths']) ? implode("\n", $tour['paths']) : '',
    '#description' => t('Enter one path per line, for example "node/1" or @front for the front page.', array('@front' => '<front>')),
    '#required' => TRUE,
  );
  $form['description'] = array(
    '#type' => 'textarea',
    '#title' => t('Description'),
    '#rows' => 3,
    '#default_value' => isset($tour['description']) ? $tour['description'] : '',
  );
  $form['auto_start'] = array(
    '#type' => 'checkbox',
    '#title' => t('Auto Start'),
    '#default_value' => isset($tour['auto_start']) ? $tour['auto_start'] : '',
  );
  $form['enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enabled'),
    '#default_value' => isset($tour['enabled']) ? $tour['enabled'] : 1,
  );
  $form['content'] = array(
    '#type' => 'container',
    '#attributes' => array('class' => array('tour-content')),
    '#prefix' => '<div id="steps-fieldset-wrapper">',
    '#suffix' => '</div>',
  );
  if(!empty($tour) && !$form_state['is_new']) {
    $form['content']['add_more'] = array(
      '#prefix' => '<ul class="action-links"><li>',
      '#suffix' => '</li></ul>',
      '#type' => 'item',
      '#markup' => l(
        t('Add a step'),
        'admin/config/user-interface/tour/ui/'. $form_state['tour']['name'] . '/step/add',
        array(
          'attributes' => array(
            'class' => array('use-ajax block-item'),
            'data-dialog' => TRUE,
            'data-dialog-options' => json_encode(array('dialogClass' => 'tour-dialog')),
          )
        )
      ),
    );
  }
  $form['content']['table'] = array(
    '#type' => 'container',
    '#theme' => 'tour_ui_edit_tour_table',
    '#attributes' => array('class' => array('tour-table')),
  );
  if(!$form_state['is_new']) {
    $form_state['content'] = $tour['steps'];
  }

  if(!empty($tour) && !$form_state['is_new']) {
    $form['content']['table']['tour'] = array(
      '#type' => 'value',
      '#value' => $tour,
    );
    foreach ($form_state['content'] as $i => $step) {
      $form['content']['table'][$i]['title'] = array(
        '#markup' => $step['title'],
      );
      $form['content']['table'][$i]['weight'] = array(
        '#type' => 'weight',
        '#title' => t('Weight'),
        '#default_value' => isset($step['weight']) ? $step['weight'] : 10,
        '#delta' => 10,
        '#title_display' => 'invisible',
      );
      $form['content']['table'][$i]['operations'] = array(
        '#type' => 'dropbutton',
        '#links' => array(
          'configure' => array(
            'title' => t('Edit'),
            'href' => 'admin/config/user-interface/tour/ui/' . $tour['name'] . '/step/' . $step['id'],
            'attributes' => array(
              'class' => array('use-ajax'),
              'data-dialog' => TRUE,
              'data-dialog-options' => json_encode(array('dialogClass' => 'tour-dialog')),
            ),
          ),
          'delete' => array(
            'title' => t('Delete'),
            'href' => 'admin/config/user-interface/tour/ui/' . $tour['name'] . '/step/' . $step['id'] . '/delete',
            'attributes' => array(
              'class' => array('use-ajax'),
            ),
          ),
        ),
      );
    }
  }
  
  $form['#attached'] = array(
    'library' => array(
      array('system', 'backdrop.ajax'),
    ),
  );
  $submit_text = $form_state['is_new'] ? t('Save and add steps') : t('Save Changes');

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => $submit_text,
  );
  if(!empty($tour) && !$form_state['is_new']) {
    $form['actions']['cancel'] = array(
      '#type' => 'submit',
      '#value' => t('Cancel'),
      '#validate' => array(),
      '#limit_validation_errors' => array(),
      '#submit' => array('tour_ui_edit_tour_reset'),
    );
  }
  return $form;
}

/**
 * Form validation handler for tour_ui_edit_tour().
 *
 * @see tour_ui_edit_tour_submit().
 */
function tour_ui_edit_tour_reset($form, &$form_state) {
  $tour = $form_state['tour'];
  tour_ui_clear_tempstore($tour['name']);
  backdrop_set_message(t('Tour changes discarded.'));
  $form_state['redirect'] = 'admin/config/user-interface/tour';
}

/**
 * Form validation handler for tour_ui_edit_tour().
 *
 * @see tour_ui_edit_tour_submit().
 */
function tour_ui_edit_tour_validate($form, &$form_state) {
  form_state_values_clean($form_state);
  
  unset($form_state['values']['actions']);
  
  // Cleanup multiline textareas
  $paths = tour_ui_format_lines($form_state['values']['paths']);
  
  // Validate paths
  foreach($paths as $path) {
    if (!backdrop_valid_path($path)) {
      if (!backdrop_lookup_path('source', $path)) {
        form_set_error('paths', t('The path @path is invalid.', array('@path' => $path)));
      }
    }
  }
  $form_state['values']['paths'] = $paths;
}


/**
 * Form submission handler for tour_ui_edit_tour().
 *
 * @see tour_ui_edit_tour_validate().
 */
function tour_ui_edit_tour_submit($form, &$form_state) {  
  form_state_values_clean($form_state);
  $tour = $form_state['tour'];

  $name = $form_state['values']['name'];
  $content = $form_state['values']['content'];
  unset($form_state['values']['content']);
  
  $config = config('tour.tour.' . $name);
  foreach ($form_state['values'] as $key => $value) {
    $config->set($key, $value);
  }
  // This is not a new tour being added so save steps from tempstore.
  if (!$form_state['is_new']) {
    // Add weights, sort by weight, then remove weights.
    foreach ($tour['steps'] as $index => $step) {
      $tour['steps'][$index]['weight'] = $content['table'][$index]['weight'];
    }
    backdrop_sort($tour['steps'], array('weight'));
    // foreach ($tour['steps'] as $index => $step) {
      // unset($tour['steps'][$index]['weight']);
    // }

    $config->set('steps', $tour['steps']);
  }

  $config->save();
  backdrop_static_reset('tour_load_all');
  cache_flush('cache');
  tour_ui_clear_tempstore($name);
  if ($form_state['is_new']) {
    $form_state['redirect'] = 'admin/config/user-interface/tour/ui/' . $name;
  }
  else {
    $form_state['redirect'] = 'admin/config/user-interface/tour/ui';
  }
}

/**
 * Render API callback: Checks if a field machine name is taken.
 *
 * @param $value
 *   The machine name, not prefixed with 'field_'.
 *
 * @return
 *   Whether or not the field machine name is taken.
 */
function tour_name_exists($value) {
  $tours = tour_load_all();
  return isset($tours[$value]);
}

/**
 * Returns HTML for the tour edit form.
 *
 * @param $variables
 *   An associative array containing:
 *   - form: A render element representing the form.
 *
 * @ingroup themeable
 */
function theme_tour_ui_edit_tour_table($variables) {
  backdrop_add_css(backdrop_get_path('module', 'tour') . '/shepherd/shepherd.css');
  backdrop_add_js(backdrop_get_path('module', 'tour_ui') . '/tour_ui.js');
  $tour = $variables['form']['tour']['#value'];
  unset($variables['form']['tour']);
  $form = $variables['form'];

  $rows = array();
  $output = '';
  foreach (element_children($form) as $id) {
    $step = $tour['steps'][$id];
    $form[$id]['weight']['#attributes']['class'] = array('tour-ui-weight');
    unset($form[$id]['title']);
    $rows[] = array(
      'data' => array(
        theme('tour_step_row', array('step' => $step)),
        backdrop_render($form[$id]['operations']),
        backdrop_render($form[$id]['weight']),
      ),
      'class' => array('draggable'),
    );
  }

  $header = array(t('Steps'), t('Configure'), t('Weight'));

  $table_id = 'tour-content';

  $output .= theme('table', array(
    'header' => $header,
    'rows' => $rows,
    'attributes' => array('id' => $table_id),
  ));

  $output .= backdrop_render_children($form);

  backdrop_add_tabledrag($table_id, 'order', 'sibling', 'tour-ui-weight');

  return $output;
}


/**
 * Returns HTML for the tour edit form.
 *
 * @param $variables
 *   An associative array containing:
 *   - form: A render element representing the form.
 *
 * @ingroup themeable
 */
function tour_ui_edit_step($form, &$form_state, $tour, $id = 'add') {
  $step = array();

  if ($id == 'add') {
    $weights = array();
    foreach ($tour['steps'] as $tour_step) {
      $weights[] = $tour_step['weight'];
    }
    $form['weight'] = array(
      '#type' => 'value',
      '#value' => max($weights) + 1,
    );
  }
  $form_state['tour'] = $tour;
  $step = isset($tour['steps'][$id]) ? $tour['steps'][$id] : $step;
  $form_state['id'] = $id;
  if (isset($step['text']['format'])) {
    $step_text = $step['text']['value'];
    $format = $step['text']['format'];
  }
  else {
    $step_text =  isset($step['text']) ? $step['text'] : '';
    $format = 'filtered_html';
  }
  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Step title'),
    '#required' => TRUE,
    '#default_value' => isset($step['title']) ? $step['title'] : '',
  );
  $form['text'] = array(
    '#type' => 'text_format',
    '#title' => t('Step text'),
    '#rows' => 2,
    '#format' => $format,
    '#required' => TRUE,
    '#default_value' => $step_text,
  );
  $form['selector'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Selector'),
    '#default_value' => isset($step['selector']) ? $step['selector'] : '',
  );
  $form['jump'] = array(
    '#type' => 'textfield',
    '#title' => t('Destination'),
    '#default_value' => isset($step['jump']) ? $step['jump'] : '',
    '#autocomplete_path' => 'path-autocomplete',
    '#placeholder' => t('(Optional) path for multi-page tours.'),
  );

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save Changes'),
    '#ajax' => array(
      'callback' => 'tour_ui_step_ajax_dialog_submit',
    ),
  );
  $form['actions']['cancel'] = array(
    '#type' => 'submit',
    '#value' => t('Cancel'),
    '#limit_validation_errors' => array(),
    '#submit' => array(),
    '#ajax' => array(
      'callback' => 'tour_ui_ajax_cancel_dialog',
    ),
  );

  return $form;
}


/**
 * Form validation handler for tour_ui_edit_tour().
 *
 * @see tour_ui_edit_tour_submit().
 */
function tour_ui_edit_step_validate($form, &$form_state) {
  form_state_values_clean($form_state);
  
  unset($form_state['values']['actions']);

  if ($form_state['id'] == 'add') {
    module_load_include('inc', 'system', 'system.admin');
    $id = system_transliterate_machine_name(strtolower($form_state['values']['title']), array());

    $form_state['values']['id'] = tour_step_unique_id($form_state['tour']['steps'], $id);
  }
  else {
    $form_state['values']['id'] = $form_state['id'];
  }
} 

/**
 * Form submission handler for tour_ui_edit_tour().
 *
 * @see tour_ui_edit_tour_validate().
 */
function tour_ui_edit_step_submit($form, &$form_state) {  
  $tour = $form_state['tour'];
  $step = $form_state['values'];

  $tour['steps'][$step['id']] = $step;

  tour_ui_set_tempstore($tour);
  $form_state['tour'] = $tour;
  backdrop_static_reset('tour_load_all');
  cache_flush('cache');
  $form_state['redirect'] = 'admin/config/user-interface/tour/ui/' . $tour['name'];
}


/**
 * Callback to delete a step.
 */
function tour_ui_delete_step($tour, $step_to_remove) {
  foreach ($tour['steps'] as $index => $step) {
    if (isset($step['id']) && $step['id'] == $step_to_remove) {
      $removed_step = $tour['steps'][$index];
      unset($tour['steps'][$index]);
      break;
    }
  }

  tour_ui_set_tempstore($tour);
  $commands = array();
  if (backdrop_is_ajax()) {
    $tour_ui_edit_form = backdrop_get_form('tour_ui_edit_tour', $tour);
    $step_table_html = backdrop_render($tour_ui_edit_form['content']);
    $commands[] = ajax_command_replace('#steps-fieldset-wrapper', $step_table_html);

    return array(
      '#type' => 'ajax',
      '#commands' => $commands,
    );
  }
  else {
    backdrop_set_message(t('Step "@title" removed.', array('@title' => $removed_step['title'])));
    backdrop_goto('admin/config/user-interface/tour/ui/' . $tour['name']);
  }

  backdrop_static_reset('tour_load_all');
  cache_flush('cache');
}  

/**
 * AJAX handler that cancels the edit dialog.
 */
function tour_ui_ajax_cancel_dialog($form, $form_state) {
  $commands = array();
  $commands[] = ajax_command_close_modal_dialog();

  return array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );
}

/**
 * AJAX handler that cancels the edit dialog.
 */
function tour_ui_step_ajax_dialog_submit($form, $form_state) {
  $commands = array();
  $commands[] = ajax_command_close_modal_dialog();
  if (form_get_errors()) {
    $html = '';
    $html .= theme('status_messages');
    $html .= backdrop_render($form);
    $title = isset($form['#title']) ? $form['#title'] : backdrop_get_title();
    $commands[] = ajax_command_open_modal_dialog($title, $html, array('dialogClass' => 'tour-dialog'));
  }
  else {
    $tour_ui_edit_form = backdrop_get_form('tour_ui_edit_tour', $form_state['tour']);
    $step_table_html = backdrop_render($tour_ui_edit_form['content']);
    $commands[] = ajax_command_replace('#steps-fieldset-wrapper', $step_table_html);
  }

  return array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );
}

/**
 * Cleans up input from multiline textareas.
 *
 */
function tour_ui_format_lines($text) {  
  // Cleanup text
  $text = explode("\n", $text);
  $text = array_map('trim', $text);
  $text = array_filter($text, 'strlen');
  return $text;
}

/**
 * Implements hook_theme().
 *
 */
function tour_ui_theme() {
  return array(
    'tour_ui_edit_tour_table' => array(
      'render element' => 'form',
    ),
    'tour_demo' => array(
      'variables' => array(),
      'template' => 'templates/tour-demo',
    ),
    'tour_step_row' => array(
      'variables' => array('step' => NULL),
      'template' => 'templates/tour-step-row',
    ),
  );
}

/**
 * Implements hook_theme().
 *
 */
function tour_ui_preprocess_tour_step_row(&$variables) {
  $step = $variables['step'];
  if (isset($step['text']['format'])) {
    $step_text = $step['text']['value'];
  }
  else {
    $step_text =  isset($step['text']) ? $step['text'] : '';
  }
  $variables['step_title'] = filter_xss($step['title']);
  $variables['step_text'] = filter_xss($step_text);
}

 /**
 * Implements hook_config_info().
 * Provides two tour files: one with default tours for demo purposes and one 
 * which is blank, for storing user-created tours.
 */
function tour_ui_config_info() {
  $prefixes['tour.tour.auto_start'] = array(
    'label' => t('tour Default Tour - Autostart'),
    'group' => t('tour'),
  );
  $prefixes['tour.tour.manual_trigger'] = array(
    'label' => t('tour Custom Tour- Manual trigger'),
    'group' => t('tour'),
  );
  return $prefixes;
}


/**
 * Get a tour currently being edited from the tempstore.
 *
 * @param string $name
 *   The machine name of the tour to load.
 */
function tour_ui_tempstore_load($name) {
  $caches = &backdrop_static(__FUNCTION__, array());
  if (!isset($caches[$name])) {
    // Try loading from tempstore first to get in-progress changes.
    $item = tempstore_get('tour', $name);
    if (!$item) {
      $item = tour_load($name);
    }
    $caches[$name] = $item;
  }

  return $caches[$name];
}

/**
 * Store changes to a tour in the temporary store.
 *
 * @param $item
 *   The tour to save into tempstore.
 */
function tour_ui_set_tempstore($item) {
  if (empty($item['name'])) {
    return;
  }

  $item['locked'] = array(
    'uid' => $GLOBALS['user']->uid,
    'updated' => REQUEST_TIME,
  );
  tempstore_set('tour', $item['name'], $item, 604800);
}

/**
 * Remove an tour from the object cache.
 */
function tour_ui_clear_tempstore($name) {
  tempstore_clear('tour', $name);
}

/**
 * Implements hook_js_alter().
 */
function tour_ui_js_alter(&$js) {
  $cdn = 'https://unpkg.com/@popperjs/core@2';
  $js[$cdn] = backdrop_js_defaults();
  $js[$cdn]['data'] = $cdn;
  $js[$cdn]['type'] = 'external';
  $js[$cdn]['every_page'] = TRUE;
  $js[$cdn]['every_page_weight'] = -1;
  $js[$cdn]['weight'] = -100;
  $js[$cdn]['group'] = JS_LIBRARY;
}
