<?php


/**
* Implements hook_menu().
*/
function tour_menu() {
  $items['tour-link-ajax/%tour'] = array(
  'title' => 'tour_builder form',
  'page callback' => 'tour_link_ajax_form',
  'page arguments' => array(1),
  'access callback' => TRUE,
  'type' => MENU_CALLBACK,
    'theme callback' => 'ajax_base_page_theme',
  );

  return $items;
}

/**
 * Implements hook_libraries_info().
 * Return information about external libraries.
 *
 */
function tour_library_info() {
  $libraries['shepherd'] = array(
    'title' => 'Shepherd',
    'website' => 'https://github.com/shipshapecode/shepherd',
    'version' => '1.2',
    'js' => array(
      backdrop_get_path('module', 'tour') . '/shepherd/shepherd.min.js' => array(),
      // backdrop_get_path('module', 'tour') . '/shepherd/shepherd.min.js.map' => array(),
    ),
    'css' => array(
      backdrop_get_path('module', 'tour') . '/shepherd/shepherd.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_init().
 * Perform setup tasks for non-cached page requests.
 *
 */
function tour_init() {
  $active_tours = tour_get_path_tours();
  tour_add_tours($active_tours);
}


/**
 *  Checks if any tour is active on a given path.
 *  
 */
function tour_get_path_tours() {
  $tours = tour_load_all();
  $active_tours = array();
  foreach($tours as $name => $tour) {
    if($tour['enabled']) {
      foreach($tour['paths'] as $path) {
        if ($path == current_path() || $path == request_path() || ($path == '<front>' && request_path() == '')) {
          $active_tours[$name] = $tour;
        }
      }
    }
  }

  return $active_tours;
}


/**
 *  Adds necessary javascript to the page to run a tour.
 *  
 */
function tour_add_tours($active_tours) {
  // $js_name = 'js/tour.min.js';
  // $base_path = './libraries/tour';

  // if (!$library_loaded) {
    // backdrop_set_message(t('Can\'t load tour library. Please download !url  plugin and extract it to @path, so @js can be found at @full_path. Also please purge version info from tour file names (both .js and .css)', array(
      // '!url' => l(t('tour'), 'https://github.com/linkedin/tour'),
      // '@path' => $base_path,
      // '@js' => $js_name,
      // '@full_path' => $base_path . '/' . $js_name,
    // )), 'error');
    // return FALSE;
  // }

  dpm($active_tours);
  $js_settings = array();
  $auto_start = FALSE;

  foreach ($active_tours as $tour_id => $tour) {
    $items = [];
    if (!empty($tour['auto_start'])) {
      $auto_start = TRUE;
    }

    $total_steps = 0;
    foreach ($tour['steps'] as $tip) {
      $total_steps = count($tour['steps']);
    }
    foreach ($tour['steps'] as $index => $tip) {
      $classes = [
        // 'tip-module-' . Html::getClass($tourEntity->getModule()),
        // 'tip-type-' . Html::getClass($tip->getPluginId()),
        // 'tip-' . Html::getClass($tip->id()),
      ];

      $selector = $tip['tour_stop_css'];
      $location = 'bottom'; // $tip['tour_stop_css'];

      $output = [
        'text' => $tip['text'],
        'title' => $tip['title'],
      ];


      if ($output) {
        $items[] = [
          'id' => $tip['id'],
          'selector' => $selector,
          'module' => 'tour',
          'type' => 'tour',
          'counter' => t('@tour_item of @total', [
            '@tour_item' => $index + 1,
            '@total' => $total_steps,
          ]),
          'attachTo' => [
             'element' => $selector,
             'on' => $location,
          ],
          // Shepherd expects classes to be provided as a string.
          'classes' => implode(' ', $classes),
        ] + $output;
      }
    }

    // If there is at least one tour item, build the tour.
    if ($items) {
      end($items);
      $key = key($items);
      $items[$key]['cancelText'] = t('End tour');
    }

    $build = array();

    // If at least one tour was built, attach tips and the tour library.
    if ($items) {
      $build['tourShepherdConfig'] = [
        'defaultStepOptions' => [
          'classes' => 'backdrop-tour',
          'cancelIcon' => [
            'enabled' => TRUE,
            'label' => t('Close'),
          ],
          'modalOverlayOpeningPadding' => 3,
          'scrollTo' => [
            'behavior' => 'smooth',
            'block' => 'center',
          ],
          'popperOptions' => [
            'modifiers' => [
              // Prevent overlap with the element being highlighted.
              [
                'name' => 'offset',
                'options' => [
                  'offset' => [-10, 20],
                ],
              ],
              // Pad the arrows so they don't hit the edge of rounded corners.
              [
                'name' => 'arrow',
                'options' => [
                  'padding' => 12,
                ],
              ],
              // Disable Shepherd's focusAfterRender modifier, which results in
              // the tour item container being focused on any scroll or resize
              // event.
              [
                'name' => 'focusAfterRender',
                'enabled' => FALSE,
              ],

            ],
          ],
        ],
        'useModalOverlay' => TRUE,
      ];

      $build['_tour_internal'] = $items;
      $build['autoStart'] = !empty($tour['auto_start']);
      $js_settings['tourContext']['tours'][$tour_id] = $build;
    }
  }
  $js_settings['tourContext']['autoStart'] = $auto_start;
  dpm($js_settings);
  backdrop_add_js($js_settings, 'setting');
  backdrop_add_library('tour', 'shepherd');
  backdrop_add_js(backdrop_get_path('module', 'tour') . '/inc/js/tour_context.js', array('scope' => 'footer', 'weight' => 5));
  backdrop_add_css(backdrop_get_path('module', 'tour') . '/inc/tour_context.css');
}

/**
 * Callback function for loading all tours.
 */
function tour_load_all() {
  $tours = &backdrop_static(__FUNCTION__);
  if (!isset($tours)) {
    if ($cache = cache_get('tour_tours')) {
      $tours = $cache->data;
    }
    else {
      // Find all modules providing tours.
      $all_tours = config_get_names_with_prefix('tour.tour');
      $tours = array();
      // Go through and load each config
      foreach($all_tours as $tour) {
        $config = config($tour);
        // Load the 'tours' config key
        $setting = $config->get();
        // $setting['config_name'] = $tour;
        $tours[$setting['name']] = $setting;
      }
      cache_set('tour_tours', $tours, 'cache');
    }
  }
  return $tours;
}

/**
 * Callback function for loading one tour by $name.
 */
function tour_load($name) {
  $tours = tour_load_all();
  if(isset($tours[$name])) {
    return $tours[$name];
  }
  return array();
}

/**
 * Implements hook_theme().
 *
 */
function tour_theme($existing, $type, $theme, $path) {
  return array(
    'tour_start_link' => array(
      'variables' => array('link_title' => NULL, 'options' => array(), 'tour_name' => NULL),
      'template' => 'templates/tour-start-link',
      'file' => 'inc/tour.theme.inc',
    ),
  );
}

/**
 * Implements hook_block_info().
 * Define all blocks provided by the module.
 *
 */
function tour_block_info() {
  $blocks['tour_start_link'] = array(
    'info' => t('Available tours'),
    'description' => t('Provides a list of themed start links for tour tours.')
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 * Return a rendered or renderable view of a block.
 *
 */
function tour_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'tour_start_link':
      $block['subject'] = 'Available tours';
      $block['content'] = tour_block_view_build();
      break;
  }
  return $block;
}

/**
 * Return a list of links for the block.
 *
 */
function tour_block_view_build() {
  $active_tours = tour_get_path_tours();
  // tour_add_tours($active_tours);

  $links = array();
  foreach($active_tours as $tour) {
    $links[] = theme('tour_start_link', array('tour_name' => $tour['name'], 'link_title' => $tour['title']));
    // $links[] = l(
        // t('Click me!'),
        // 'tour-link-ajax/' . $tour['name'],
        // array(
          // 'attributes' => array(
            // 'class' => array('use-ajax tour-edit-link'),
          // )
        // )
      // );

  }
  if($links) {
    return theme('item_list', array('items' => $links));
  }
  return '';
}

function tour_link_ajax_form($tour) {
  tour_add_tours(array($tour));
  $commands = array();
  $return = array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );
  return $return;
}
